services:
  backend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - GIN_ENV=production
      - GIN_MODE=release
    volumes:
      - ./backend/static:/app/backend/static
    env_file:
        - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
    - taher

  db:
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - taher

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
      ]
    command: ["up"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taher


volumes:
  postgres_data:

networks:
  taher:
    external: true
