services:
  backend:
    build: ./backend
    env_file:
        - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/backend/static
    depends_on:
      - frontend
    networks:
      - taher

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - taher

  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    networks:
      - taher
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?sslmode=disable"
      ]
    command: ["up"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taher

volumes:
  postgres_data:

networks:
  taher:
    external: true
