services:
  backend:
    build: ./backend
    env_file:
        - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/backend/static
    depends_on:
      - frontend
    networks:
      - taher

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - taher

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: taher
      POSTGRES_PASSWORD: alfayad
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taher

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./backend/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://taher:alfayad@db:5432/portfolio?sslmode=disable"
      ]
    command: ["up"]
    networks:
      - taher

volumes:
  postgres_data:

networks:
  taher:
    external: true
