CREATE TABLE blog (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMPTZ DEFAULT now(),
	content TEXT,
	metadata JSONB
);

ALTER TABLE images ALTER COLUMN site DROP DEFAULT;
ALTER TABLE images ALTER COLUMN site TYPE TEXT USING site::text;
ALTER TABLE images ALTER COLUMN caption DROP NOT NULL;
DROP TYPE image_site;
